// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class Calendar
    {
        public int Id { get; set; }
        public int? UserId { get; set; }
        public int? DayId { get; set; }
        public int? ScheduleId { get; set; }

        public virtual Day Day { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}