// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class CatConsultorio
    {
        public CatConsultorio()
        {
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string Consultorio { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}