// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class CatOptionDiagnostic
    {
        public CatOptionDiagnostic()
        {
            Results = new HashSet<Result>();
        }

        public int Id { get; set; }
        public string Section { get; set; }
        public string Clave { get; set; }
        public string VariableName { get; set; }
        public string Abbreviation { get; set; }
        public string Filling { get; set; }
        public string TypeVariable { get; set; }
        public string Screen { get; set; }

        public virtual ICollection<Result> Results { get; set; }
    }
}