// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class Quiz
    {
        public Quiz()
        {
            Results = new HashSet<Result>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool? Result { get; set; }
        public string TextResult { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual ICollection<Result> Results { get; set; }
    }
}