// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class Schedule
    {
        public Schedule()
        {
            Calendars = new HashSet<Calendar>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string TimeInicial { get; set; }
        public string TimeFin { get; set; }

        public virtual ICollection<Calendar> Calendars { get; set; }
    }
}