// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace biz.main.tecnicah.Entities
{
    public partial class User
    {
        public User()
        {
            Calendars = new HashSet<Calendar>();
            RequestSupports = new HashSet<RequestSupport>();
            Results = new HashSet<Result>();
            UserLogIns = new HashSet<UserLogIn>();
        }

        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string ProfessionalLicense { get; set; }
        public int? SpecialityId { get; set; }
        public int? ConsultorioId { get; set; }
        public bool? ProfessionalLicenseProcedure { get; set; }
        public int RoleId { get; set; }
        public bool? Status { get; set; }
        public string Phone { get; set; }
        public DateTime? DateBirth { get; set; }
        public string FirstName { get; set; }
        public string ConsultingType { get; set; }
        public int? Sex { get; set; }
        public string Address { get; set; }
        public string Institution { get; set; }
        public int? StateId { get; set; }
        public string Other { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual CatConsultorio Consultorio { get; set; }
        public virtual CatRole Role { get; set; }
        public virtual CatSpeciality Speciality { get; set; }
        public virtual CatState State { get; set; }
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<RequestSupport> RequestSupports { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<UserLogIn> UserLogIns { get; set; }
    }
}